# Generated by Django 2.2.2 on 2019-06-21 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190620_1929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogger',
            options={'ordering': ['blogger', 'bio']},
        ),
        migrations.AlterField(
            model_name='blogger',
            name='bio',
            field=models.TextField(help_text='A brief biography of the user', max_length=500),
        ),
        migrations.AlterField(
            model_name='blogger',
            name='blogger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
