# Generated by Django 2.2.2 on 2019-06-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190621_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post',
            field=models.TextField(help_text='Enter text of your blog post here.', max_length=3000),
        ),
    ]
